version: '3.1'

services:
  app:
    build:
      context: .
    container_name: spring-batch-app
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - dependencies-network
    environment:
      POSTGRESQL_URL: jdbc:postgresql://postgres:5432/db
      POSTGRESQL_USER: user
      POSTGRESQL_PASSWORD: password

  postgres:
    image: "postgres:11"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    networks:
      - dependencies-network

networks:
  dependencies-network:
    driver: bridge

volumes:
  postgres_data: