server:
  port: 8080

spring:
  application:
    name: financial-transaction
  datasource:
    url: ${POSTGRESQL_URL:jdbc:postgresql://localhost:5432/db}
    username: ${POSTGRESQL_USER:user}
    password: ${POSTGRESQL_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

